### ISSUE TITLE
isFloat function consider int as float

### ISSUE THREAD

**Issue by GuillaumeDespaux** [algosup/2023-2024-project-3-virtual-processor-team-2#18]
The isFloat function consider Int as Float 
e.g. 10 == float
Group name : isFloat
Unit test name : is10

**Comment by MaximeAlgosup** [comment]
It's not an issue it's an int is supposed to be considered as a float.
For example:
10(int) -> 10.00(float)

It is why in the parser we checked if the value is an int before checking if it's a float
