### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by MathiasGagnepain** [algosup/2023-2024-project-3-virtual-processor-team-2#42]
these links doesn't work

![image](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145995367/b7025980-b795-492a-8677-7a3fbf17f8ba)

**Comment by MathiasGagnepain** [comment]
Broken too
![image](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145995367/03ef9bd1-53fa-479a-92c0-ab589966d329)

**Comment by EnzoGuillouche** [comment]
All the broken links that have been found are now fixed.

**Comment by EnzoGuillouche** [comment]
Fixed.

**Comment by MathiasGagnepain** [comment]
![image](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145995367/f26f28a8-b4d0-42af-a15b-b95be5dc7852)

**Comment by EnzoGuillouche** [comment]
The table of content has been updated.

**Comment by MathiasGagnepain** [comment]
![image](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145995367/eb733af8-5412-489a-94d8-4b217c7d550c)
