### ISSUE TITLE
Convention Weekly 6 issue

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-3-virtual-processor-team-2#43]
<img width="356" alt="image" src="https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145991192/c7adf99b-16b7-4dfb-a5df-a59b274772c3">

The convention with the "-ing-" verbs you began has been broken with the 3rd point.

**Comment by MathiasGagnepain** [comment]
Fixed
