### ISSUE TITLE
Typos and Convention Weekly 6 issues

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-3-virtual-processor-team-2#44]
<img width="307" alt="image" src="https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/assets/145991192/32e4f359-5deb-462b-b018-03c75e81f05d">

The "ing"s need to be removed. 
Also, "github" written this way does not follow the convention you put just before.

**Comment by MathiasGagnepain** [comment]
Fixed
