### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-3-virtual-processor-team-2#60]
In the 2AT2 description, there is "2AT2 stands for AAssembler for Assembly Team 2".

**Comment by EnzoGuillouche** [comment]
"IAT2" is still mentioned in the README.

**Comment by MathiasGagnepain** [comment]
fixed in https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2/commit/ecdc488f5891c4747e09c2803bd3e0134c830297
