### ISSUE TITLE
Github Wiki: several remarks

### ISSUE THREAD

**Issue by PaulNowak36** [algosup/2023-2024-project-3-virtual-processor-team-2#68]
-Control flow instruction part could be entirely merged into a single chart 

-Each example of the control flow functions should be more detailed 

-What “ngr” abbrevation come from btw ? 

-ob1 shouldn’t be here, he couldn’t even prevent AnaKeyn to fall to the dark side 

-less equal instead of less= you should type  

-the additions examples should start with mov rg1, num1 and mov rg2, num2 + mov var1, num3 

-”Mov instruction” is too sober for a chapter title 

-Couldn’t we also merge “mov instructions” with “control flow instructions and “stack operations” ? 

-Are “mov instructions” examples necessary at this point ? 

-Perhaps a guide on how to use/install cmake to run the program ?! 

-For pusha, in which order are pushed each register ? 

-Can we even push the register 3 ? 

-Maybe one big and clear example with the pusha and popa functions ? 

-Project architecture: builder has a mistake 

-What does the first schema represent ? 

-”var management” part merged with another chapter ? 

-No Lifo explanation ?

**Comment by Guillaume18100** [comment]
-Control flow instruction part could be entirely merged into a single chart done

**Comment by Guillaume18100** [comment]
-Each example of the control flow functions should be more detailed done

**Comment by Guillaume18100** [comment]
Its an abbreviation for a japanese word that means "fleeing" or something like that

**Comment by Guillaume18100** [comment]
-ob1 shouldn’t be here, he couldn’t even prevent AnaKeyn to fall to the dark side good one mate

**Comment by Guillaume18100** [comment]
-less equal instead of less= you should type done

**Comment by Guillaume18100** [comment]
-”Mov instruction” is too sober for a chapter title done 

-Couldn’t we also merge “mov instructions” with “control flow instructions and “stack operations” ? done

**Comment by Guillaume18100** [comment]
-Are “mov instructions” examples necessary at this point ? Yes

**Comment by Guillaume18100** [comment]
-Perhaps a guide on how to use/install cmake to run the program ?! done

**Comment by Guillaume18100** [comment]
-For pusha, in which order are pushed each register ? tbh idk

**Comment by Guillaume18100** [comment]
-Project architecture: builder has a mistake. Resolved

**Comment by Guillaume18100** [comment]
-What does the first schema represent ? Explained
